import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";

export const metadata = {
    title: "Terms of Service | MailApply Platform",
    description: "Our terms and conditions for using the MailApply AI job outreach platform.",
};

export default function TermsOfService() {
    return (
        <div className="bg-white min-h-screen flex flex-col">
            <Navbar />

            {/* Professional Header */}
            <div className="pt-32 pb-16 bg-slate-50 border-b border-slate-100">
                <div className="max-w-4xl mx-auto px-6">
                    <h1 className="text-4xl md:text-5xl font-black font-heading text-slate-900 tracking-tight mb-4">
                        Terms of Service
                    </h1>
                    <p className="text-slate-500 font-medium italic">
                        By using MailApply, you agree to these legal obligations.
                    </p>
                </div>
            </div>

            <main className="flex-grow py-16 md:py-24">
                <div className="max-w-4xl mx-auto px-6">
                    <article className="prose prose-slate prose-lg max-w-none prose-headings:font-heading prose-headings:font-black prose-headings:tracking-tight prose-a:text-primary-600 prose-strong:text-slate-900">
                        <section className="bg-slate-50 p-8 rounded-3xl border border-slate-100 mb-16">
                            <h3 className="mt-0 text-slate-900">TL;DR (The Simplified Version)</h3>
                            <ul className="mb-0 text-sm md:text-base text-slate-600">
                                <li><strong>Goal:</strong> We help you send cold emails to recruiters.</li>
                                <li><strong>Responsibility:</strong> You must review AI content before it goes out. No spamming.</li>
                                <li><strong>Ownership:</strong> Your account is yours; don't share it.</li>
                                <li><strong>No Guarantee:</strong> We don't guarantee you'll get a job, but we'll try our best.</li>
                            </ul>
                        </section>

                        <section>
                            <h2 className="text-2xl font-black text-slate-900">1. Acceptance of Terms</h2>
                            <p>
                                Welcome to MailApply (the "Service"). By creating an account or using the platform, you agree to be bound by these Terms of Service. If you do not agree to all of these terms, you are prohibited from using the Service.
                            </p>
                        </section>

                        <section className="mt-16">
                            <h2 className="text-2xl font-black text-slate-900">2. Service Scope</h2>
                            <p>
                                MailApply provides AI-powered tools to assist in job applications, including email generation and direct inbox delivery. We reserve the right to modify, suspend, or discontinue any part of the Service at any time without notice.
                            </p>
                        </section>

                        <section className="mt-16">
                            <h2 className="text-2xl font-black text-slate-900">3. User Obligations</h2>
                            <div className="p-6 border-l-4 border-primary-500 bg-slate-50 my-8">
                                <h4 className="mt-0">Prohibited Use Cases:</h4>
                                <ul className="text-sm space-y-2 mb-0">
                                    <li>Sending bulk marketing or promotional spam.</li>
                                    <li>Harassing recruiters or hiring managers.</li>
                                    <li>Using the Service to impersonate individuals or entities.</li>
                                    <li>Attempting to scrape or exploit our AI generation engines.</li>
                                </ul>
                            </div>
                            <p>Failure to comply with these obligations will result in immediate termination of your account without refund.</p>
                        </section>

                        <section className="mt-16">
                            <h2 className="text-2xl font-black text-slate-900">4. AI-Generated Content Disclaimer</h2>
                            <p>
                                MailApply uses generative artificial intelligence to produce email drafts.
                            </p>
                            <div className="bg-orange-50 p-6 rounded-2xl border border-orange-100 text-orange-900 text-sm">
                                <strong>Important:</strong> You are the "Sender of Record." You must review, edit, and approve every email generated by our AI. MailApply is not liable for errors, inaccuracies, or offensive content produced by the AI model.
                            </div>
                        </section>

                        <section className="mt-16">
                            <h2 className="text-2xl font-black text-slate-900">5. Limitation of Liability</h2>
                            <p>
                                In no event shall MailApply or its founders be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the Service. Use of the Service is at your own risk.
                            </p>
                        </section>

                        <section className="mt-16">
                            <hr className="border-slate-100 mb-12" />
                            <p className="text-sm text-slate-400">
                                For full legal inquiries or to report a violation of these terms, please contact our legal department at <a href="mailto:legal@mailapply.in">legal@mailapply.in</a>.
                            </p>
                        </section>
                    </article>
                </div>
            </main>

            <Footer />
        </div>
    );
}
